[package]
name = "llm-web-fe"
version = "0.1.0"
authors = ["Worik root@worik.org"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
# jsonwebtoken = "8.3.0"
base64 = "0.21.2"
chrono = { version = "0.4", features = ["wasmbind"] }
getrandom = { version = "0.2", features = ["js"] }
gloo-storage = "0.2.2"
hmac = "0.12.1"
js-sys = "0.3"
jwt = { git = "https://github.com/mikkyang/rust-jwt", branch = "master" }
llm-web-common = {path = "../llm-web-common"}
parking_lot = { version = "0.11.1", features = ["wasm-bindgen"]}
rand = "0.8.5"
rsa = "0.9.2"
serde  = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.6"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlDivElement',
  'HtmlElement',
  'HtmlInputElement',
  'HtmlTextAreaElement',
  'MouseEvent',
  'Node',
  'Text',
  'Window',
  'console'
]
